Fix: create two functions, one for get and one for count
jsuarez19/holbertonschool-AirBnB_clone_v3 pull request #1
Opened 2023-09-26 22:24 UTC by yerti

Hello Jose, in the classes I added two functions: the get function, which is a method to retrieve an object, and the count function, which is a method to count the number of objects.
 Please check if they are correct but to correct them

2023-09-26 23:33 UTC, jsuarez19 requested changes
Please add comments to the functions that don't have them. Apart from that, I see everything very well-structured, and you shouldn't have any issues running it.

2023-09-26 23:33 UTC, jsuarez19 commented on models/engine/db_storage.py
> +        for obj in models.storage.all(cls).values():
I think it will be helpful if you explain in a comment what the function **get** will do when it's called

2023-09-26 23:33 UTC, jsuarez19 commented on models/engine/db_storage.py
> +    def count(self, cls=None):
Same here, even if you can tell at first sight what hte function **count** will do, for future improvements will be helpful to have a comment

2023-09-26 23:33 UTC, jsuarez19 commented on models/engine/file_storage.py
> +    def get(self, cls, id):
Same as before, kindly add a comment to explain the function

2023-09-26 23:33 UTC, jsuarez19 commented on models/engine/file_storage.py
> +    def count(self, cls=None):
Same as before, kindly add a comment to explain the function

2023-09-27 00:27 UTC, yerti commented
I already added the comments to each function created, please review them

2023-09-27 00:39 UTC, jsuarez19 approved these changes
Thanks, the comments are ok

2023-09-27 00:40 UTC, merged